roomrent/urls.py
from django.contrib import admin
from django.urls import path,include
from datawork import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from schema_graph.views import Schema

urlpatterns = [
    path("schema/", Schema.as_view()),
    path('admin/', admin.site.urls),
    path('',views.home,name="homepage"),
    path('room_request/<str:rq_id>', views.room_request, name="room_request"),
    path('city_search',views.city_search,name="city_search"),
    path('search_room',views.search_room,name="search_room"),
    path('room_type/<slug:rt_id>',views.room_type,name="room_type"),
    path('house_view/<slug:h_id>', views.house_view,name="house_view"),
    path('room_view/<slug:r_id>', views.room_view,name="room_view"),
    path('logins/',views.logins,name="logins"),
    path('logouts/',views.logouts,name="logouts"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
    #password reset----------------------------
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    #room renter--------------------------------
    path('user_register_renter/',views.user_register_renter,name="user_register_renter"),
    path('register_renter/',views.register_renter,name="register_renter"),
    path('renter_profile/',views.renter_profile,name="renter_profile"),
    path('renter_update_profile/',views.renter_update_profile,name="renter_update_profile"),
    path('renter_update_image/', views.renter_update_image, name="renter_update_image"),
    path('renter_update_id_proof/', views.renter_update_id_proof, name="renter_update_id_proof"),
    path('renter_rooms/',views.renter_rooms,name="renter_rooms"),
    path('renter_payment/',views.renter_payment,name="renter_payment"),
    path('request_delete/<str:r_id>', views.request_delete,name="request_delete"),
    path('password_change_renter/',views.password_change_renter,name="password_change_renter"),
    # room owner------------------------------
    path('user_register_owner/',views.user_register_owner,name="user_register_owner"),
    path('register_owner/',views.register_owner,name="register_owner"),
    path('owner_profile/',views.owner_profile,name="owner_profile"),
    path('owner_update_profile/', views.owner_update_profile, name="owner_update_profile"),
    path('add_house/',views.add_house,name="add_house"),
    path('owner_house/<slug:ho_id>',views.owner_house,name="owner_house"),
    path('owner_update_house/<slug:h_id>',views.owner_update_house,name="owner_update_house"),
    path('owner_update_image/',views.owner_update_image,name="owner_update_image"),
    path('owner_update_id_proof/<slug:h_id>',views.owner_update_id_proof,name="owner_update_id_proof"),
    path('owner_rooms/<slug:r_id>',views.owner_rooms,name="owner_rooms"),
    path('add_room/<slug:r_id>',views.add_room,name="add_room"),
    path('room_active/<slug:a_id>',views.room_active,name="room_active"),
    path('room_pending/<slug:p_id>',views.room_pending,name="room_pending"),
    path('room_allot/<slug:alt_id>',views.room_allot,name="room_allot"),
    path('owner_payment/',views.owner_payment,name="owner_payment"),
    path('owner_payment_paid/',views.owner_payment_paid,name="owner_payment_paid"),
    path('owner_payment_gen/',views.owner_payment_gen,name="owner_payment_gen"),
    path('owner_payment_due/',views.owner_payment_due,name="owner_payment_due"),
    path('owner_payment_advance/',views.owner_payment_advance,name="owner_payment_advance"),
    path('password_change_owner/',views.password_change_owner,name="password_change_owner"),
    path('my_renter/<slug:rt_id>',views.my_renter,name="my_renter"),
    path('room_allot_request/',views.room_allot_request,name="room_allot_request"),
    path('room_request_active/<str:al_id>',views.room_request_active,name="room_request_active"),
    path('room_allot_pending/',views.room_allot_pending,name="room_allot_pending"),
    path('roomallot/active/<str:a_id>', views.allot_active,name="allot_active"),
    path('roomallot/pending/<str:p_id>', views.allot_pending,name="allot_pending"),
    path('roomallot/delete/<str:d_id>', views.allot_delete,name="allot_delete"),
    path('view_renter_profile/<str:rnt_id>', views.view_renter_profile,name="view_renter_profile"),
    path('owner_room_view/<str:rm_id>', views.owner_room_view,name="owner_room_view"),
    path('owner_room_edit/<slug:et_id>', views.owner_room_edit,name="owner_room_edit"),
    path('owner_room_query',views.owner_room_query,name="owner_room_query"),
    path('query_delete/<int:q_id>',views.query_delete,name="query_delete"),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

datawork/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from datetime import datetime
# from django.contrib.gis.db import models


class State(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(State, self).save(*args,**kwargs)


class City(models.Model):
    name = models.CharField(max_length=100)
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(City, self).save(*args,**kwargs)


class RoomOwner(models.Model):
    ro_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    ro_image = models.ImageField(upload_to="profile")
    ro_contact = models.CharField(max_length=10,unique=True)
    ro_street = models.CharField(max_length=200)
    ro_id_proof = models.ImageField(upload_to="profile/proof")
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    city = models.ForeignKey(City,on_delete=models.CASCADE)

    def delete(self, *args, **kwargs):
        self.ro_image.delete()
        self.ro_id_proof.delete()
        super(RoomOwner, self).delete(*args, **kwargs)

    def __str__(self):
        return self.user_id.first_name


class OwnerHouse(models.Model):
    ho_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    ho_contact = models.CharField(max_length=10,unique=True)
    ho_street = models.CharField(max_length=200)
    house_name = models.CharField(max_length=100)
    house_image = models.ImageField(upload_to="image")
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    city = models.ForeignKey(City,on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)
    #location = models.PointField()



    def save(self,*args,**kwargs):
        self.slug = slugify(self.house_name)
        super(OwnerHouse, self).save(*args,**kwargs)

    def delete(self, *args, **kwargs):
        self.house_image.delete()
        super(OwnerHouse, self).delete(*args, **kwargs)

    def __str__(self):
        return self.house_name


class RoomType(models.Model):
    rt_id = models.AutoField(primary_key=True)
    rt_title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.rt_title

    def save(self,*args,**kwargs):
        self.slug = slugify(self.rt_title)
        super(RoomType, self).save(*args,**kwargs)


class Room(models.Model):
    r_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    house_id = models.ForeignKey(OwnerHouse,on_delete=models.CASCADE)
    r_title = models.CharField(max_length=100)
    r_rent = models.IntegerField()
    r_type = models.ForeignKey(RoomType,on_delete=models.DO_NOTHING)
    r_desc = models.CharField(max_length=200)
    r_image = models.ImageField(upload_to="image")
    slug = models.SlugField()
    r_status = models.CharField(max_length=20, default='1',choices=(("0", "Pending"), ("1", "Active")))
    r_doc = models.DateTimeField(default=datetime.now(), blank=True)

    def delete(self, *args, **kwargs):
        self.r_image.delete()
        super(Room, self).delete(*args, **kwargs)

    def __str__(self):
        return self.r_title+' | '+self.r_type.rt_title


class RoomRenter(models.Model):
    rr_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    rr_contact = models.CharField(max_length=10,unique=True)
    rr_image = models.ImageField(upload_to="profile")
    rr_street = models.CharField(max_length=200)
    state = models.ForeignKey(State,on_delete=models.DO_NOTHING)
    city = models.ForeignKey(City,on_delete=models.DO_NOTHING)
    rr_id_proof = models.ImageField(upload_to="profile/proof")

    def delete(self, *args, **kwargs):
        self.rr_image.delete()
        self.rr_id_proof.delete()
        super(RoomRenter, self).delete(*args, **kwargs)

    def __str__(self):
        return self.user_id.first_name


class RoomAllot(models.Model):
    ra_id = models.AutoField(primary_key=True)
    ra_room_id = models.ForeignKey(Room, on_delete=models.DO_NOTHING)
    house_id = models.ForeignKey(OwnerHouse, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='user_id')
    renter = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='renter')
    ra_doc = models.DateTimeField(default=datetime.now(), blank=True)
    ra_status = models.CharField(max_length=20, default='1',choices=(("0", "Request"), ("1", "Active"),("2","Pending")))
    slug = models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.ra_room_id.r_title+' | '+self.renter.username


class RoomQuery(models.Model):
    m_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    m_name = models.CharField(max_length=100)
    m_contact = models.CharField(max_length=10)
    m_message = models.CharField(max_length=200)
    m_doc = models.DateTimeField(default=datetime.now(), blank=True)

    def __str__(self):
        return self.user_id.username+'|'+self.m_name


class PaymentGenerate(models.Model):
    pg_id = models.AutoField(primary_key=True)
    pg_txn = models.CharField(max_length=100)
    user_id = models.ForeignKey(User,on_delete=models.DO_NOTHING, related_name='user_renter')
    owner = models.ForeignKey(User,on_delete=models.DO_NOTHING, related_name='user_owner')
    pg_amount = models.IntegerField()
    pg_month = models.DateTimeField()
    pg_allot_id = models.ForeignKey(RoomAllot,on_delete=models.DO_NOTHING)
    pg_doc = models.DateTimeField(default=datetime.now(), blank=True)
    slug = models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.pg_txn+' | '+self.pg_allot_id.ra_room_id.r_title+' | '+self.user_id.username

    def save(self,*args,**kwargs):
        self.slug = slugify(self.pg_txn)
        super(PaymentGenerate, self).save(*args,**kwargs)


class PaymentPaid(models.Model):
    pp_id = models.AutoField(primary_key=True)
    pp_txn = models.CharField(max_length=100)
    renter_id = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='renter_id')
    owner_id = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='owner_id')
    pp_amount = models.IntegerField()
    pp_allot_id = models.ForeignKey(RoomAllot,on_delete=models.DO_NOTHING)
    pp_doc = models.DateTimeField(default=datetime.now(), blank=True)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return self.pp_txn+' | '+self.pp_allot_id.ra_room_id.r_title+' | '+self.renter_id.username

    def save(self, *args, **kwargs):
        self.slug = slugify(self.pp_txn)
        super(PaymentPaid, self).save(*args, **kwargs)

templates/roomrenter/renter_update_profile.html
{% extends 'roomrenter/rr_base.html' %}
{% block content %}
<div class="col-lg-9 bg-white mb-2">
    {% for foo in messages %}
                                <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ foo }}
                                </div>
                        {% endfor %}
<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="card border-0 shadow">
            <div class="card-header  text-center bg-transparent">Update Profile</div>
            <div class="card-body">
                <form action="{% url 'renter_update_profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.label }}
                        {{ form }}
                    </div>
                    <div class="form-group">
                        {{ profile }}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-block btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/roomrenter/rr_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Room Rent</title>
    {% load static %}
    {% load template_tags %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-light sticky-top shadow-sm">
    <div class="container">
        <a href="{% url 'homepage' %}" class="navbar-brand text-dark text-uppercase "><h2 class="font-weight-bold">Room Rent</h2></a>
        <ul class="navbar-nav ml-auto">


            {% if request.user.is_authenticated %}
                {%  if request.user|has_group:"renter" %}
                    <li class="nav-item"><a href="{% url 'renter_profile' %}" class="nav-link text-muted ml-2">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                {% elif request.user|has_group:"owner" %}
                    <li class="nav-item"><a href="{% url 'owner_profile' %}" class="nav-link text-muted ml-2">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                {% else %}
                {% endif %}
            <li class="nav-item"><a href="{% url 'logouts' %}" class="nav-link text-light btn btn-danger btn-sm">Logout</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'user_register_renter' %} " class="nav-link text-muted">Renter Register</a></li>
                <li class="nav-item"><a href="{% url 'user_register_owner' %}" class="nav-link text-muted">Owner Register</a></li>
                <li class="nav-item"><a href="{% url 'logins' %}" class="nav-link text-muted">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-lg-3">
                <div class="card shadow-sm border-0">
                    <center>
                    <img src="{{ user.0.rr_image.url }}" class="shadow-sm mt-2 rounded" width="50%" height="170px" alt="logo">
                    <form action="{% url 'renter_update_image' %}" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                        <label class="update_image">
                        <input type="file" hidden class="form-control" name="rr_image" onchange="this.form.submit()">
                            <i class="fas fa-edit fa-lg "></i>
                        </label>
                    </form>
                    <div class="card-body">
                        <h1 class="text-truncate h6 p-0 m-0  text-center text-uppercase text-muted">{{ userdata.0.first_name }} {{ userdata.0.last_name }}</h1>
                    </div>
                    <ul class="list-group mt-1 " style="text-decoration: underline;">
                          <li class="list-group-item border-0"><a href="{% url 'renter_profile' %}" class="nav-link small p-0 m-0 text-muted">Dashboard</a></li>
                          <li class="list-group-item border-0"><a href="{% url 'renter_payment' %}" class="nav-link small p-0 m-0 text-muted ">Payment</a></li>
                          <li class="list-group-item border-0"><a href="{% url 'renter_rooms' %}" class="nav-link small p-0 m-0 text-muted ">My Rooms</a></li>
                          <li class="list-group-item border-0"><a href="{% url 'password_change_renter' %}" class="nav-link small p-0 m-0 text-muted ">Settings</a></li>
                </ul>
                   </center>
                </div>

            </div>
            {% block content %}{% endblock %}
        </div>
    </div>
{% block footer %}{% endblock %}

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
        $(document).ready(function () {
            $(".form-group>input,select,textarea").addClass("form-control")
        })
    </script>
</html>

templates/roomrenter/rr_password_change.html
{% extends 'roomrenter/rr_base.html' %}
{% block content %}
    <div class="col-lg-9">
    <div class="row">
        <div class="col-lg-5 mx-auto">
            <div class="card border-0 shadow-sm">
                <div class="card-header bg-transparent">Password Change</div>
                <div class="card-body">
                    <form action="{% url 'password_change_renter' %}" method="post">
                      {% csrf_token %}
                        {% for foo in messages %}
                                <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ foo }}
                                </div>
                            {% endfor %}
                      <div class="form-group small">
                                {{ form.label_tag }}
                                {{ form }}
                          <label for="" class="text-danger">{{ form.errors }}</label>
                      </div>
                        <div class="form-group small">
                            <input type="submit" value="Save" class="btn btn-block btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/roomrenter/rr_payment.html
{% extends 'roomrenter/rr_base.html' %}
{% load template_tags %}
{% block content %}
<div class="col-lg-9">
{% for rm in room %}
    <div class="card mt-2 mb-2 border-0 shadow-sm" >
    <div class="card-header bg-transparent small">
        <div class="form-inline text-muted">
            Room no: <a href="{% url 'room_view' rm.ra_room_id.r_id %}" class="nav-link text-primary text-capitalize ml-2 m-0 p-0"> <span class="badge badge-primary p-1">{{ rm.ra_room_id.r_title }}</span> of {{ rm.ra_room_id.house_id.ho_id|room_owner_house }}</a>
            <span class="text-warning ml-auto">Rent:  ₹{{ rm.ra_room_id.r_rent }} / {{ rm.ra_room_id|room_allot_count }} Renter</span>
            <span class=" ml-auto">
                {% if rm|cond %}
                      <span class="text-danger">Due: ₹ {{ rm|subtract }}</span>
                {% else  %}
                    <span class="text-success">Advance : ₹ {{ rm|subtract }}</span>
                {% endif %}
            </span>
            <span class="mx-auto text-info">
                Status :
                {% if rm.ra_status == '1' %}
                    <span class="text-success">Active</span>
                {% elif rm.ra_status == '2' %}
                    <span class="text-danger">Pending</span>
                {% else %}
                    <span class="text-danger">Request</span>
                {% endif %}
            </span>
        </div>
    </div>
    <div class="card-body m-1 p-1">
        <div class="row mb-2">
    <div class="col-lg-6">
        <div class="card border-0">
                <div class="card-header small border-0">Payment Generate <span class="float-right text-danger">Total: ₹ {{ rm|sum_pg_amount }} </span></div>
                <div class="card-body ">
                    <table class="table table-responsive-sm table-borderless">
                        <tr class="small">
                            <th>Txno.</th>
                            <th>Amount</th>
                            <th>Month</th>
                        </tr>
                        {% for pg in rm.paymentgenerate_set.all %}

                        <tr class="small">
                            <td>{{ pg.pg_txn }}</td>
                            <td>₹ {{ pg.pg_amount }}</td>
                            <td>{{ pg.pg_month|date:'M,Y' }}</td>
                        </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4"><div class="alert alert-danger h6 text-center p-3" role="alert">No Payment Generate availables!</div></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
    </div>
     <div class="col-lg-6">
        <div class="card border-0">
                <div class="card-header small border-0">Payment Paid <span class="float-right text-primary"> Total: ₹ {{ rm|sum_pp_amount }}</span></div>
                <div class="card-body ">
                    <table class="table table-responsive-sm table-borderless">
                        <tr class="small">
                            <th>Txno.</th>
                            <th>Amount</th>
                            <th>Date</th>
                        </tr>
                        {% for pp in rm.paymentpaid_set.all %}
                        <tr class="small">
                            <td>{{ pp.pp_txn }}</td>
                            <td>₹ {{ pp.pp_amount }}</td>
                            <td>{{ pp.pp_doc|date:'d M,Y' }}</td>
                        </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4"><div class="alert alert-danger h6 text-center p-3" role="alert">No Payment Paid availables!</div></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
    </div>
</div>
    </div>
   </div>
{% empty %}
    <div class="alert alert-danger h6 text-center p-3" role="alert">No room availables!</div>
{% endfor %}
</div>
{% endblock %}

templates/roomrenter/rr_profile.html
{% extends 'roomrenter/rr_base.html' %}
{% load template_tags %}
{% block content %}
<div class="col-lg-9">
    {% for foo in messages %}
                                <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ foo }}
                                </div>
                        {% endfor %}
<div class="row shadow-sm">
    <div class="col-lg-4 ">
            <img src="{{ user.0.rr_id_proof.url }}" alt="" class="rounded" width="100%" height="250px">
            <form action="{% url 'renter_update_id_proof' %}" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="edit_image text-muted">
                        <input type="file" hidden class="form-control" name="id_proof" onchange="this.form.submit()">
                            UPDATE ID Proof <i class="fas fa-image fa-lg "></i>
                        </label>
                    </div>
                </form>
    </div>
    <div class="col-lg-8">
        <div class="card border-0">
            <div class="card-header bg-transparent">
                 <div class="form-inline">
            <h4 class="" style="text-decoration: underline;">Profile Details</h4>
            <a href="{% url 'renter_update_profile' %}" class="m-0 p-0 ml-auto"><i class="fas fa-edit fa-lg text-secondary"></i></a>
        </div>
            </div>
            <div class="card-body small">
                <table class="table table-responsive-sm table-borderless">
                    <tr>
                        <th>Name</th>
                        <td>{{ userdata.0.first_name }} {{ userdata.0.last_name }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ userdata.0.email }}</td>
                    </tr>
                    <tr>
                        <th>Contact</th>
                        <td>{{ user.0.rr_contact }}</td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td>{{ user.0.rr_street }},{{ user.0.city }},{{ user.0.state }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-12 mt-2">
        <div class="card border-0">
            {% for foo in messages %}
                <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ foo }}
                </div>
            {% endfor %}
            <div class="card-header bg-transparent" style="text-decoration: underline;">Room Request</div>
            <div class="card-body">
                <table class="table table-responsive-sm table-borderless">
                    <tr class="small">
                        <th>Room</th>
                        <th>House Name</th>
                        <th>Room Owner</th>
                        <th>Contact</th>
                        <th>View</th>
                        <th>Date</th>
                        <th>Delete</th>
                    </tr>
                    {% for rq in room_request %}
                                    <tr class="small">
                                        <td class="">{{ rq.ra_room_id.r_title }}</td>
                                        <td>{{ rq.house_id.ho_id|room_owner_house }}</td>
                                        <td><a href="{% url 'house_view' rq.house_id.ho_id|room_owner_slug %}" class="nav-link p-0 m-0">{{ rq.user_id.first_name }} {{ rq.user_id.last_name }}</a></td>

                                        <td>{{ rq.house_id.ho_id|room_owner_contact }}</td>

                                        <td><a href="{% url 'room_view' rq.ra_room_id.r_id %}" class="nav-link p-0 m-0"><i class="fas fa-eye fa-lg text-primary"></i></a></td>
                                        <td>{{ rq.ra_doc|date:'d M,Y' }}</td>
                                        <td>
                                            <div class="form-inline">
                                                <a href="{% url 'request_delete' rq.ra_id %}" class=" nav-link p-0 m-0 ml-2"><i class="far fa-times-circle fa-lg text-danger"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                    {% empty %}
                        <tr>
                            <td colspan="8"><div class="alert alert-danger h6 text-center p-3" role="alert">No renter request availables!</div></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-7 mt-2"></div>
</div>
</div>
{% endblock %}