roomrent/urls.py
from django.contrib import admin
from django.urls import path,include
from datawork import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from schema_graph.views import Schema

urlpatterns = [
    path("schema/", Schema.as_view()),
    path('admin/', admin.site.urls),
    path('',views.home,name="homepage"),
    path('room_request/<str:rq_id>', views.room_request, name="room_request"),
    path('city_search',views.city_search,name="city_search"),
    path('search_room',views.search_room,name="search_room"),
    path('room_type/<slug:rt_id>',views.room_type,name="room_type"),
    path('house_view/<slug:h_id>', views.house_view,name="house_view"),
    path('room_view/<slug:r_id>', views.room_view,name="room_view"),
    path('logins/',views.logins,name="logins"),
    path('logouts/',views.logouts,name="logouts"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
    #password reset----------------------------
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    #room renter--------------------------------
    path('user_register_renter/',views.user_register_renter,name="user_register_renter"),
    path('register_renter/',views.register_renter,name="register_renter"),
    path('renter_profile/',views.renter_profile,name="renter_profile"),
    path('renter_update_profile/',views.renter_update_profile,name="renter_update_profile"),
    path('renter_update_image/', views.renter_update_image, name="renter_update_image"),
    path('renter_update_id_proof/', views.renter_update_id_proof, name="renter_update_id_proof"),
    path('renter_rooms/',views.renter_rooms,name="renter_rooms"),
    path('renter_payment/',views.renter_payment,name="renter_payment"),
    path('request_delete/<str:r_id>', views.request_delete,name="request_delete"),
    path('password_change_renter/',views.password_change_renter,name="password_change_renter"),
    # room owner------------------------------
    path('user_register_owner/',views.user_register_owner,name="user_register_owner"),
    path('register_owner/',views.register_owner,name="register_owner"),
    path('owner_profile/',views.owner_profile,name="owner_profile"),
    path('owner_update_profile/', views.owner_update_profile, name="owner_update_profile"),
    path('add_house/',views.add_house,name="add_house"),
    path('owner_house/<slug:ho_id>',views.owner_house,name="owner_house"),
    path('owner_update_house/<slug:h_id>',views.owner_update_house,name="owner_update_house"),
    path('owner_update_image/',views.owner_update_image,name="owner_update_image"),
    path('owner_update_id_proof/<slug:h_id>',views.owner_update_id_proof,name="owner_update_id_proof"),
    path('owner_rooms/<slug:r_id>',views.owner_rooms,name="owner_rooms"),
    path('add_room/<slug:r_id>',views.add_room,name="add_room"),
    path('room_active/<slug:a_id>',views.room_active,name="room_active"),
    path('room_pending/<slug:p_id>',views.room_pending,name="room_pending"),
    path('room_allot/<slug:alt_id>',views.room_allot,name="room_allot"),
    path('owner_payment/',views.owner_payment,name="owner_payment"),
    path('owner_payment_paid/',views.owner_payment_paid,name="owner_payment_paid"),
    path('owner_payment_gen/',views.owner_payment_gen,name="owner_payment_gen"),
    path('owner_payment_due/',views.owner_payment_due,name="owner_payment_due"),
    path('owner_payment_advance/',views.owner_payment_advance,name="owner_payment_advance"),
    path('password_change_owner/',views.password_change_owner,name="password_change_owner"),
    path('my_renter/<slug:rt_id>',views.my_renter,name="my_renter"),
    path('room_allot_request/',views.room_allot_request,name="room_allot_request"),
    path('room_request_active/<str:al_id>',views.room_request_active,name="room_request_active"),
    path('room_allot_pending/',views.room_allot_pending,name="room_allot_pending"),
    path('roomallot/active/<str:a_id>', views.allot_active,name="allot_active"),
    path('roomallot/pending/<str:p_id>', views.allot_pending,name="allot_pending"),
    path('roomallot/delete/<str:d_id>', views.allot_delete,name="allot_delete"),
    path('view_renter_profile/<str:rnt_id>', views.view_renter_profile,name="view_renter_profile"),
    path('owner_room_view/<str:rm_id>', views.owner_room_view,name="owner_room_view"),
    path('owner_room_edit/<slug:et_id>', views.owner_room_edit,name="owner_room_edit"),
    path('owner_room_query',views.owner_room_query,name="owner_room_query"),
    path('query_delete/<int:q_id>',views.query_delete,name="query_delete"),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

datawork/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from datetime import datetime
# from django.contrib.gis.db import models


class State(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(State, self).save(*args,**kwargs)


class City(models.Model):
    name = models.CharField(max_length=100)
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(City, self).save(*args,**kwargs)


class RoomOwner(models.Model):
    ro_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    ro_image = models.ImageField(upload_to="profile")
    ro_contact = models.CharField(max_length=10,unique=True)
    ro_street = models.CharField(max_length=200)
    ro_id_proof = models.ImageField(upload_to="profile/proof")
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    city = models.ForeignKey(City,on_delete=models.CASCADE)

    def delete(self, *args, **kwargs):
        self.ro_image.delete()
        self.ro_id_proof.delete()
        super(RoomOwner, self).delete(*args, **kwargs)

    def __str__(self):
        return self.user_id.first_name


class OwnerHouse(models.Model):
    ho_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    ho_contact = models.CharField(max_length=10,unique=True)
    ho_street = models.CharField(max_length=200)
    house_name = models.CharField(max_length=100)
    house_image = models.ImageField(upload_to="image")
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    city = models.ForeignKey(City,on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)
    #location = models.PointField()



    def save(self,*args,**kwargs):
        self.slug = slugify(self.house_name)
        super(OwnerHouse, self).save(*args,**kwargs)

    def delete(self, *args, **kwargs):
        self.house_image.delete()
        super(OwnerHouse, self).delete(*args, **kwargs)

    def __str__(self):
        return self.house_name


class RoomType(models.Model):
    rt_id = models.AutoField(primary_key=True)
    rt_title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.rt_title

    def save(self,*args,**kwargs):
        self.slug = slugify(self.rt_title)
        super(RoomType, self).save(*args,**kwargs)


class Room(models.Model):
    r_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    house_id = models.ForeignKey(OwnerHouse,on_delete=models.CASCADE)
    r_title = models.CharField(max_length=100)
    r_rent = models.IntegerField()
    r_type = models.ForeignKey(RoomType,on_delete=models.DO_NOTHING)
    r_desc = models.CharField(max_length=200)
    r_image = models.ImageField(upload_to="image")
    slug = models.SlugField()
    r_status = models.CharField(max_length=20, default='1',choices=(("0", "Pending"), ("1", "Active")))
    r_doc = models.DateTimeField(default=datetime.now(), blank=True)

    def delete(self, *args, **kwargs):
        self.r_image.delete()
        super(Room, self).delete(*args, **kwargs)

    def __str__(self):
        return self.r_title+' | '+self.r_type.rt_title


class RoomRenter(models.Model):
    rr_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    rr_contact = models.CharField(max_length=10,unique=True)
    rr_image = models.ImageField(upload_to="profile")
    rr_street = models.CharField(max_length=200)
    state = models.ForeignKey(State,on_delete=models.DO_NOTHING)
    city = models.ForeignKey(City,on_delete=models.DO_NOTHING)
    rr_id_proof = models.ImageField(upload_to="profile/proof")

    def delete(self, *args, **kwargs):
        self.rr_image.delete()
        self.rr_id_proof.delete()
        super(RoomRenter, self).delete(*args, **kwargs)

    def __str__(self):
        return self.user_id.first_name


class RoomAllot(models.Model):
    ra_id = models.AutoField(primary_key=True)
    ra_room_id = models.ForeignKey(Room, on_delete=models.DO_NOTHING)
    house_id = models.ForeignKey(OwnerHouse, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='user_id')
    renter = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='renter')
    ra_doc = models.DateTimeField(default=datetime.now(), blank=True)
    ra_status = models.CharField(max_length=20, default='1',choices=(("0", "Request"), ("1", "Active"),("2","Pending")))
    slug = models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.ra_room_id.r_title+' | '+self.renter.username


class RoomQuery(models.Model):
    m_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    m_name = models.CharField(max_length=100)
    m_contact = models.CharField(max_length=10)
    m_message = models.CharField(max_length=200)
    m_doc = models.DateTimeField(default=datetime.now(), blank=True)

    def __str__(self):
        return self.user_id.username+'|'+self.m_name


class PaymentGenerate(models.Model):
    pg_id = models.AutoField(primary_key=True)
    pg_txn = models.CharField(max_length=100)
    user_id = models.ForeignKey(User,on_delete=models.DO_NOTHING, related_name='user_renter')
    owner = models.ForeignKey(User,on_delete=models.DO_NOTHING, related_name='user_owner')
    pg_amount = models.IntegerField()
    pg_month = models.DateTimeField()
    pg_allot_id = models.ForeignKey(RoomAllot,on_delete=models.DO_NOTHING)
    pg_doc = models.DateTimeField(default=datetime.now(), blank=True)
    slug = models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.pg_txn+' | '+self.pg_allot_id.ra_room_id.r_title+' | '+self.user_id.username

    def save(self,*args,**kwargs):
        self.slug = slugify(self.pg_txn)
        super(PaymentGenerate, self).save(*args,**kwargs)


class PaymentPaid(models.Model):
    pp_id = models.AutoField(primary_key=True)
    pp_txn = models.CharField(max_length=100)
    renter_id = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='renter_id')
    owner_id = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name='owner_id')
    pp_amount = models.IntegerField()
    pp_allot_id = models.ForeignKey(RoomAllot,on_delete=models.DO_NOTHING)
    pp_doc = models.DateTimeField(default=datetime.now(), blank=True)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return self.pp_txn+' | '+self.pp_allot_id.ra_room_id.r_title+' | '+self.renter_id.username

    def save(self, *args, **kwargs):
        self.slug = slugify(self.pp_txn)
        super(PaymentPaid, self).save(*args, **kwargs)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Room Rent</title>
     {% load static %}
    {% load template_tags %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-light sticky-top shadow-sm">
    <div class="container">
        <a href="{% url 'homepage' %}" class="navbar-brand text-dark text-uppercase "><h2 class="font-weight-bold">Room Rent</h2></a>
        <ul class="navbar-nav ml-auto">


            {% if request.user.is_authenticated %}
                {%  if request.user|has_group:"renter" %}
                    <li class="nav-item"><a href="{% url 'renter_profile' %}" class="nav-link text-muted ml-2">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                {% elif request.user|has_group:"owner" %}
                    <li class="nav-item"><a href="{% url 'owner_profile' %}" class="nav-link text-muted ml-2">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                {% else %}
                {% endif %}
            <li class="nav-item"><a href="{% url 'logouts' %}" class="nav-link text-light btn btn-danger btn-sm">Logout</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'user_register_renter' %} " class="nav-link text-muted">Renter Register</a></li>
                <li class="nav-item"><a href="{% url 'user_register_owner' %}" class="nav-link text-muted">Owner Register</a></li>
                <li class="nav-item"><a href="{% url 'logins' %}" class="nav-link text-muted">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}{% endblock %}
{% block footer %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
        $(document).ready(function () {
            $(".form-group>input,select,textarea").addClass("form-control");
             $("#id_state").change(function () {
                const url = $("#register").attr("data-cities-url");  // get the url of the `load_cities` view
                const stateId = $(this).val();  // get the selected country ID from the HTML input

                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'state_id': stateId       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                    }
                });

            });
             $('#city_search').select2({
            ajax: {
                url: '{% url 'city_search' %}',
                dataType: 'json',
                processResults: function (response_content) {
                    return {
                        results: $.map(response_content, function (item) {
                            return {id: item.name, text: item.name};
                        })
                    };
                }
            },
            minimumInputLength: 2
        });
        });
    </script>
</html>
{#$(function () {#}
{#                $("#city").autocomplete({#}
{#                    source: '{% url 'city_search' %}',#}
{#                    minLength: 2#}
{#                });#}
{#            });#}

templates/city_dropdown_list_options.html
<option value="">Choose</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Room Rent</title>
     {% load static %}
    {% load template_tags %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>
<header role="banner">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'homepage' %}">Room Rent</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample05">
              <ul class="navbar-nav ml-auto">


            {% if request.user.is_authenticated %}
                {%  if request.user|has_group:"renter" %}
                    <li class="nav-item"><a href="{% url 'renter_profile' %}" class="nav-link ml-2">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                {% elif request.user|has_group:"owner" %}
                    <li class="nav-item"><a href="{% url 'owner_profile' %}" class="nav-link ml-2">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                {% else %}
                {% endif %}
            <li class="nav-item"><a href="{% url 'logouts' %}" class="nav-link text-light btn btn-danger btn-sm p-1 mt-4">Logout</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'user_register_renter' %} " class="nav-link">Renter Register</a></li>
                <li class="nav-item"><a href="{% url 'user_register_owner' %}" class="nav-link">Owner Register</a></li>
                <li class="nav-item"><a href="{% url 'logins' %}" class="nav-link">Login</a></li>
            {% endif %}
        </ul>
            </ul>
          </div>
        </div>

      </nav>
    </header>
<div class="hero" style="background-image: url({% static 'images/background.jpg' %});"></div>
    <div class="container" style="margin-top:-500px;">
<form action="{% url 'search_room' %}" method="get" >
    <div class="row">
        <div class="col-lg-10 col-9">
            <select name="city_search" id="city_search" class="form-control" style="height:200px;">
                <option selected disabled="true">Search city</option>
            </select>
        </div>
        <div class="col-lg-2 col-3">
            <input type="submit" value="search" class="btn btn-info btn-block p-1 rounded-0" style="font-size:12px;">
        </div>
    </div>
</form>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
        $(document).ready(function () {
            $(".form-group>input,select,textarea").addClass("form-control");
             $("#id_state").change(function () {
                const url = $("#register").attr("data-cities-url");  // get the url of the `load_cities` view
                const stateId = $(this).val();  // get the selected country ID from the HTML input

                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'state_id': stateId       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                    }
                });

            });
             $('#city_search').select2({
            ajax: {
                url: '{% url 'city_search' %}',
                dataType: 'json',
                processResults: function (response_content) {
                    return {
                        results: $.map(response_content, function (item) {
                            return {id: item.name, text: item.name};
                        })
                    };
                }
            },
            minimumInputLength: 2
        });
        });
    </script>
</html>

templates/house_view.html
{% extends 'base.html' %}
{% load template_tags %}
{% block content %}
    <div class="container">
    <div class="row mt-3">
        <div class="col-lg-4">
            <div class="card shadow-lg mb-2">
                <div class="card-body small">
                    <img src="{{ house.house_image.url }}" alt="" class="w-100 rounded" height="300px">
                    <h6 class="text-center text-uppercase mt-2">{{ house.house_name }}</h6>
                    <p class=" text-muted text-center">{{ house.user_id.first_name }} {{ house.user_id.last_name }} | {{ house.ho_street }} ,{{ house.city }} ,{{ house.state }}</p>
                    <p class="text-muted"><i class="fa fa-phone"></i>- {{ house.ho_contact }}</p>
                    <p class="text-muted"><i class="fa fa-envelope"></i>- {{ house.user_id.email }}</p>
                </div>
                <div class="card-body shadow m-5 rounded-pill">
                        {% for foo in messages %}
                            <div class="alert {{ foo.tags }}  alert-dismissible fade show " role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                {{ foo }}
                            </div>
                        {% endfor %}
                        <h4 class="text-center mt-4">Room Query</h4>
                        <form action="" class="small" method="post">
                        {% csrf_token %}
                        {% for form in form %}
                            <div class="form-group m-0 p-0">
                                {{ form.label_tag }}
                                {{ form }}
                                <label for="" class="text-danger">{{ form.errors }}</label>
                            </div>
                        {% endfor %}
                            <center>
                                <input type="submit" value="Send" class="btn btn-primary brn-sm">
                            </center>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            {% for r in room %}
                <div class="card mb-2 border-0 shadow">
                    <div class="card-body p-1 m-1">
                        <div class="row">
                            <div class="col-lg-5 ">
                                <a href="{% url 'room_view' r.r_id %}" class="nav-link m-0 p-0">
                                    <img src="{{ r.r_image.url }}" alt="" class="w-100" height="200px">
                                    <p class="text-muted text-center text-capitalize mt-2 m-0 p-0 bg-light">{{ r.r_title }}</p>
                                </a>
                            </div>
                            <div class="col-lg-7 small">
                                <p class="mt-3 text-success">Type:<span class="text-muted"> {{ r.r_type }}</span> <span class="float-right text-success mr-3">₹ {{ r.r_rent }}</span></p>
                                <div class="alert alert-success small text-muted " role="alert">{{ r.r_desc }}</div>

                                {% if r.r_id|room_allot_count == 0 %}
                                    {% if request.user.is_authenticated %}
                                        {%  if request.user|has_group:"renter" %}
                                            <div class="form-inline">
                                                <span class="badge badge-primary  mt-2 px-3 py-2">Empty Room Renter </span>
                                                <a href="{% url 'room_request' r.r_id %}" class="btn btn-dark ml-auto mt-1">Request for room</a>
                                            </div>
                                        {% elif request.user|has_group:"owner" %}
                                            <span class="alert alert-danger small">You can't request for room! You are a Owner</span>
                                        {% else %}
                                            <span class="alert alert-danger small">You can't request for room! You are a Admin</span>
                                        {% endif %}
                                     {% else %}
                                        <div class="form-inline">
                                            <span class="badge badge-primary  mt-2 px-3 py-2">Empty Room Renter </span>
                                            <a href="{% url 'room_request' r.r_id %}" class="btn btn-dark ml-auto mt-1 ">Request for room</a>
                                        </div>
                                     {% endif %}

                                {% else %}
                                    <div class="form-inline">
                                    <span class="badge badge-danger  mt-2 px-3 py-2">{{ r.r_id|room_allot_count }} Renter Booked</span>
                                        {% if request.user|has_group:"owner" %}
                                            <span class="alert alert-danger small mt-4 px-3 py-2 ml-2">You can't request for room! You are a Owner</span>
                                        <a href="{% url 'room_request' r.r_id %}" class="btn btn-dark ml-auto mt-1">Request for room</a>
                                         {% endif %}
                                    </div>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                  <div class="alert alert-danger h6 text-center p-3" role="alert">No room availables!</div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}